### ISSUE TITLE
[Fabric] Compatibility, rendering issue with Twilight Forest

### ISSUE THREAD

**Issue by Reimnop** [ZsoltMolnarrr/BetterCombat#66]
**Minecraft version** - 1.18.2
**Mod loader** - Fabric Loader 0.14.9
**Mod version** - 1.1.0
**I am using the latest version available** - Yes

**Describe the bug**
If Twilight Forest is installed, the player's head is rendered in first person view whenever a Better Combat animation is played, which isn't supposed to happen.

**To Reproduce**
1. Install Twilight Forest
2. Use any weapon with a Better Combat animation
3. Observe player head in first person

**Expected behavior**
There shouldn't be a player head

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/56994757/186623917-f40861f0-d4de-4252-8859-4d8a5a9477e5.png)

**Additional context**
The problem stopped occurring after I uninstalled Twilight Forest.

**Comment by InsaanNotFound** [comment]
It should be noted that disabling _firstPersonEffects = false_ in twilightforest-client.toml does not solve the issue. It seems to be somehow related to the rendering Twilight Forest implements for it, yet even disabling that certain config option does not disable their renderer. Issue occurs in both Fabric and Forge versions with Twilight Forest installed

**Comment by Reimnop** [comment]
I fixed the issue. The solution was to update to the latest version of Twilight Forest on CurseForge.

**Comment by InsaanNotFound** [comment]
Sadly, on Forge even after updating to newest TF version the issue persists.
